import type { WebhookDelivery, WebhookEndpoint } from './types';

export const WEBHOOK_ENDPOINTS_DEMO: WebhookEndpoint[] = [
  {
    id: 'demo-endpoint-1',
    name: 'Order service',
    url: 'https://example.com/hooks/myapi',
    events: ['parcel.created', 'parcel.delivered', 'parcel.failed'],
    description: 'Example endpoint for order status updates.',
    enabled: true,
    lastDelivery: 'Today, 14:22',
    createdAt: '2026-09-20T08:30:00.000Z',
  },
  {
    id: 'demo-endpoint-2',
    name: 'Warehouse integration',
    url: 'https://example.net/webhooks/parcel',
    events: ['parcel.picked_up', 'parcel.in_transit'],
    description: 'Example endpoint for warehouse tracking.',
    enabled: false,
    lastDelivery: 'Yesterday, 17:45',
    createdAt: '2026-09-18T11:00:00.000Z',
  },
];

export const WEBHOOK_DELIVERIES_DEMO: WebhookDelivery[] = [
  {
    id: 'delivery-demo-1',
    eventId: 'evt_demo_1001',
    eventType: 'parcel.delivered',
    endpointId: 'demo-endpoint-1',
    endpointName: 'Order service',
    requestUrl: 'https://example.com/hooks/myapi',
    timestamp: '2026-10-02T07:22:00.000Z',
    statusCode: 200,
    status: 'Delivered',
    attempts: [{ number: 1, attemptedAt: '2026-10-02T07:22:00.000Z', statusCode: 200, responseTimeMs: 182 }],
    responseTimeMs: 182,
    requestHeaders: { 'Content-Type': 'application/json', 'X-MyAPI-Event': 'parcel.delivered', 'X-MyAPI-Event-Id': 'evt_demo_1001' },
    requestPayload: { event: 'parcel.delivered', data: { tracking_number: 'DEMO123456', status: 'delivered' } },
    responseBody: { received: true },
  },
  {
    id: 'delivery-demo-2',
    eventId: 'evt_demo_1002',
    eventType: 'parcel.in_transit',
    endpointId: 'demo-endpoint-1',
    endpointName: 'Order service',
    requestUrl: 'https://example.com/hooks/myapi',
    timestamp: '2026-10-02T06:18:00.000Z',
    statusCode: 500,
    status: 'Failed',
    attempts: [
      { number: 1, attemptedAt: '2026-10-02T06:18:00.000Z', statusCode: 500, responseTimeMs: 410 },
      { number: 2, attemptedAt: '2026-10-02T06:23:00.000Z', statusCode: 500, responseTimeMs: 398 },
    ],
    responseTimeMs: 398,
    requestHeaders: { 'Content-Type': 'application/json', 'X-MyAPI-Event': 'parcel.in_transit', 'X-MyAPI-Event-Id': 'evt_demo_1002' },
    requestPayload: { event: 'parcel.in_transit', data: { tracking_number: 'DEMO654321', status: 'in_transit' } },
    responseBody: { error: 'Example server error' },
  },
  {
    id: 'delivery-demo-3',
    eventId: 'evt_demo_1003',
    eventType: 'parcel.created',
    endpointId: 'demo-endpoint-1',
    endpointName: 'Order service',
    requestUrl: 'https://example.com/hooks/myapi',
    timestamp: '2026-10-01T10:02:00.000Z',
    statusCode: 202,
    status: 'Delivered',
    attempts: [{ number: 1, attemptedAt: '2026-10-01T10:02:00.000Z', statusCode: 202, responseTimeMs: 96 }],
    responseTimeMs: 96,
    requestHeaders: { 'Content-Type': 'application/json', 'X-MyAPI-Event': 'parcel.created', 'X-MyAPI-Event-Id': 'evt_demo_1003' },
    requestPayload: { event: 'parcel.created', data: { tracking_number: 'DEMO778899', status: 'created' } },
    responseBody: { queued: true },
  },
];

